### ISSUE TITLE
Error when flashing on a D1_Mini

### ISSUE THREAD

**Issue by CJOWood** [wtahler/esphome-mideaXYE-rs485#1]
```
In file included from src/main.cpp:85:
src/xyeVars.h:18: warning: "T2A" redefined
   18 | #define T2A 12
      | 
In file included from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:39,
                 from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Esp.h:24,
                 from src/esphome/core/helpers.h:15,
                 from src/esphome/components/api/proto.h:5,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/esp8266_peri.h:160: note: this is the location of the previous definition
  160 | #define T2A  ESP8266_REG(0x630) //Alarm Value
      | 
Compiling .pioenvs/heat-pump-xye/libbf4/ESPAsyncTCP-esphome/SyncClient.cpp.o
Compiling .pioenvs/heat-pump-xye/libbf4/ESPAsyncTCP-esphome/tcp_axtls.c.o
In file included from src/main.cpp:85:
/config/esphome/heat-pump-xye.yaml: In lambda function:
src/xyeVars.h:4:16: error: invalid conversion from 'int' to 'SerialMode' [-fpermissive]
    4 | #define RX_PIN 1
      |                ^
      |                |
      |                int
/config/esphome/heat-pump-xye.yaml:128:42: note: in expansion of macro 'RX_PIN'
  128 |             mySerial.begin(4800, SERIAL_8N1, RX_PIN, TX_PIN);
      |                                          ^~~~~~
In file included from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:303,
                 from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Esp.h:24,
                 from src/esphome/core/helpers.h:15,
                 from src/esphome/components/api/proto.h:5,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/HardwareSerial.h:87:68: note:   initializing argument 3 of 'void HardwareSerial::begin(long unsigned int, SerialConfig, SerialMode, uint8_t)'
   87 |     void begin(unsigned long baud, SerialConfig config, SerialMode mode, uint8_t tx_pin)
      |                                                         ~~~~~~~~~~~^~~~
Archiving .pioenvs/heat-pump-xye/libbf4/libESPAsyncTCP-esphome.a
In file included from src/main.cpp:85:
/config/esphome/heat-pump-xye.yaml: In lambda function:
src/xyeVars.h:4:16: error: invalid conversion from 'int' to 'SerialMode' [-fpermissive]
    4 | #define RX_PIN 1
      |                ^
      |                |
      |                int
/config/esphome/heat-pump-xye.yaml:195:42: note: in expansion of macro 'RX_PIN'
  195 |         mySerial.begin(4800, SERIAL_8N1, RX_PIN, TX_PIN);
      |                                          ^~~~~~
In file included from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:303,
                 from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Esp.h:24,
                 from src/esphome/core/helpers.h:15,
                 from src/esphome/components/api/proto.h:5,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/HardwareSerial.h:87:68: note:   initializing argument 3 of 'void HardwareSerial::begin(long unsigned int, SerialConfig, SerialMode, uint8_t)'
   87 |     void begin(unsigned long baud, SerialConfig config, SerialMode mode, uint8_t tx_pin)
      |                                                         ~~~~~~~~~~~^~~~
In file included from src/main.cpp:85:
/config/esphome/heat-pump-xye.yaml: In lambda function:
src/xyeVars.h:4:16: error: invalid conversion from 'int' to 'SerialMode' [-fpermissive]
    4 | #define RX_PIN 1
      |                ^
      |                |
      |                int
/config/esphome/heat-pump-xye.yaml:267:44: note: in expansion of macro 'RX_PIN'
  267 |           mySerial.begin(4800, SERIAL_8N1, RX_PIN, TX_PIN);
      |                                            ^~~~~~
In file included from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:303,
                 from /data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/Esp.h:24,
                 from src/esphome/core/helpers.h:15,
                 from src/esphome/components/api/proto.h:5,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/HardwareSerial.h:87:68: note:   initializing argument 3 of 'void HardwareSerial::begin(long unsigned int, SerialConfig, SerialMode, uint8_t)'
   87 |     void begin(unsigned long baud, SerialConfig config, SerialMode mode, uint8_t tx_pin)
      |                                                         ~~~~~~~~~~~^~~~
Compiling .pioenvs/heat-pump-xye/libaf0/Hash/Hash.cpp.o
Archiving .pioenvs/heat-pump-xye/libaf0/libHash.a
Compiling .pioenvs/heat-pump-xye/lib67b/ESP8266WiFi/BearSSLHelpers.cpp.o
*** [.pioenvs/heat-pump-xye/src/main.cpp.o] Error 1
========================== [FAILED] Took 4.74 seconds ==========================
```

RX and TX pin has been changed to 1&3.

**Comment by wtahler** [comment]
Looks like T2A is used in ESP8266 core code somewhere. What is your board and framework type?

I'll change the name of the macro to something more unique so it doesn't stomp on something else, that should fix at least that problem.

**Comment by CJOWood** [comment]
> Looks like T2A is used in ESP8266 core code somewhere. What is your board and framework type from your yaml file?
> 
> I'll change the name of the macro to something more unique so it doesn't stomp on something else, that should fix at least that problem.

I am just using a d1 mini (8266) as that's what I had laying around.

**Comment by wtahler** [comment]
I changed the names, see if it works now. Can you tell me what your yaml file says for the "esphome:" block?

**Comment by wtahler** [comment]
Also, looking here: https://lastminuteengineers.com/wemos-d1-mini-pinout-reference/ it looks like you shouldn't use pins 1 and 3. Try pins 4 and 5 maybe?

**Comment by CJOWood** [comment]
> I changed the names, see if it works now. Can you tell me what your yaml file says for the "esphome:" block?

```
esphome:
  name: heat-pump-xye
  friendly_name: Heat Pump XYE
  includes:
  - xyeVars.h

esp8266:
  board: d1_mini
```

>Also, looking here: https://lastminuteengineers.com/wemos-d1-mini-pinout-reference/ it looks like you shouldn't use pins 1 and 3. Try pins 4 and 5 maybe?

Will do. I haven't tried hooking it up yet. I thought it had to use the D1 Mini's tx and rx pins.

**Comment by wtahler** [comment]
I think if you use those pins you'll have problems communicating with it via USB after that. If you make updates wirelessly I think you'll be ok?

My ESP32 has 3 UARTs, so it wasn't an issue. Yours just has one I think. 

Let me know if it works, I've got some ideas if it doesn't. I'm wondering if it will complain about how I used HardwareSerial on your board. 

I added a bunch of info to the readme regarding the temperature compensation and stuff, check it out if you want to see the rabbit hole I went down looking for info on these units haha.

**Comment by CJOWood** [comment]
> I think if you use those pins you'll have problems communicating with it via USB after that. If you make updates wirelessly I think you'll be ok?
> 
> My ESP32 has 3 UARTs, so it wasn't an issue. Yours just has one I think.
> 
> Let me know if it works, I've got some ideas if it doesn't. I'm wondering if it will complain about how I used HardwareSerial on your board.
> 
> I added a bunch of info to the readme regarding the temperature compensation and stuff, check it out if you want to see the rabbit hole I went down looking for info on these units haha.

I was just doing some research on the 8266 board and it does not like the HardwareSerial used. I tried some alternatives but don't do enough with these or ESPHome to figure it out.

**Comment by wtahler** [comment]
I played around with a D1 mini yaml file in ESPHome and got it to compile at least (I don't have one to test with).  You'll need to use GPIO pins 13/17 (might be labeled D7/D8?) for RX/TX respectively.   I updated the readme to include the instructions for ESP8266-based controllers (like the D1-mini).  Looking forward to working with you to get it up and running!

**Comment by CJOWood** [comment]
It compiled and flashed! I'll try to install it today. I am going to use external power for now, but I've seen forum posts on people that have found 5v on the board. Could also step down 24v as well, I guess.

**Comment by wtahler** [comment]
Great news! Hope you get good data.  There are lots of power sources you could pull from on the board, I'm working on pulling power from the HA/HB lines now actually. I'll let you know how it goes!

No, haven't considered pressure sensors.  You just want to see how hard the fan is pushing?

**Comment by CJOWood** [comment]
> Great news! Hope you get good data.  There are lots of power sources you could pull from on the board, I'm working on pulling power from the HA/HB lines now actually. I'll let you know how it goes!
> 
> No, haven't considered pressure sensors.  You just want to see how hard the fan is pushing?  

Yes, mostly in relation to the filter. People have used it to check when the filter is dirty.

**Comment by CJOWood** [comment]
> Great news! Hope you get good data.  There are lots of power sources you could pull from on the board, I'm working on pulling power from the HA/HB lines now actually. I'll let you know how it goes!
> 
> No, haven't considered pressure sensors.  You just want to see how hard the fan is pushing?  

Yes, mostly in relation to the filter. People have used it to check when the filter is dirty. And note the general efficiency of the motor.

**Comment by CJOWood** [comment]
The newest commit:
```
INFO ESPHome 2025.2.0
INFO Reading configuration /config/esphome/heat-pump-xye.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing heat-pump-xye (board: d1_mini; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.6
Compiling .pioenvs/heat-pump-xye/src/main.cpp.o
In file included from src/main.cpp:4:
src/xyeVars.h:23:1: error: 'Serial' does not name a type
   23 | Serial mySerial();
      | ^~~~~~
/config/esphome/heat-pump-xye.yaml: In lambda function:
/config/esphome/heat-pump-xye.yaml:38:12: error: 'mySerial' was not declared in this scope; did you mean 'Serial'?
   38 |           if (!mySerial)
      |            ^~~~~~~~
      |            Serial
/config/esphome/heat-pump-xye.yaml: In lambda function:
/config/esphome/heat-pump-xye.yaml:47:7: error: 'mySerial' was not declared in this scope; did you mean 'Serial'?
   47 |         mySerial.write(xyeVars.waitSendData,16);
      |       ^ ~~~~~~
      |       Serial
/config/esphome/heat-pump-xye.yaml: In lambda function:
/config/esphome/heat-pump-xye.yaml:77:14: error: 'mySerial' was not declared in this scope; did you mean 'Serial'?
   77 |         resp = mySerial.available();
      |              ^~~~~~~~
      |              Serial
/config/esphome/heat-pump-xye.yaml: In lambda function:
/config/esphome/heat-pump-xye.yaml:209:14: error: 'mySerial' was not declared in this scope; did you mean 'Serial'?
  209 |       resp = mySerial.available();
      |              ^~~~~~~~
      |              Serial
/config/esphome/heat-pump-xye.yaml: In lambda function:
/config/esphome/heat-pump-xye.yaml:277:20: error: 'mySerial' was not declared in this scope; did you mean 'Serial'?
  277 |       uint8_t resp=mySerial.available();
      |                    ^~~~~~~~
      |                    Serial
*** [.pioenvs/heat-pump-xye/src/main.cpp.o] Error 1
========================== [FAILED] Took 3.83 seconds ==========================
```

**Comment by CJOWood** [comment]
I reverted to the last version that compiled. I hooked up my XY-RS485 module to the Air Handler following the instructions, then connected to my D1 Mini. Unfortunately, I could not get them to talk. The TX light on the module would stay on and nothing.

The debugging is difficult because as soon as the module is connected to the D1 I can get any logs.

Recommendations on a ESP32? Haha

**Comment by wtahler** [comment]
Ah, yeah I see what I messed up on the 8266 file.  I think I fixed it (I was able to compile it), but the old one you have is probably ok as well.  When I call Serial.swap() it moves the Serial pins, did you connect to the alternate pins?  TX light staying on makes me think possibly wrong pin and it's getting a constant voltage signal.  

You can't even get logs over wireless? I can add a text_sensor that can show the last log message or something, it will get imported under the device in Home Assistant and at least give you some information.

**Comment by wtahler** [comment]
Ok, made more updates (with comments now!). I believe it will work for you, what I recommend is adding `web_server:` to your yaml file.  It MIGHT be unstable on the 8266 but it will give you a way to see the logs if you aren't getting them on wifi.  

I bought a 3-pack of ESP32-WROOM devices on Amazon for like $15 USD.  Not too bad. But I think the D1-mini will work!

**Comment by CJOWood** [comment]
Tried the newest version as I still get a permanently on LED on RX (or TX) as I've tried hooked RX and TX to D7 and D8 and swapped them just to check. I also tried a new D1 Mini to see it if the module was the problem but the new one doesn't work either.

I did order a ESP32 that's supposed to come on Wednesday... but I am happy to continue troubleshooting. I found [this blog post](https://www.bizkit.ru/en/2019/01/23/11882/) that seems to have someone with a similar issue. He solved it with SoftwareSerial.

**Comment by wtahler** [comment]
Try setting your logger section to "level: info" so you get less clutter. You'll just get the messages from my program then.

Yeah it's definitely getting SOME data. Not full packets for some reason though, that's really weird (should be 32 bytes of data received, it got 13, waited, and dumped it). There should be no activity on the line except for the ESP device, and it only sends a query packet every 15 seconds.  I'm also not sure why some of the components are taking so long for an operation, I tried to be sensitive to that and ensure that the code just does a drive-by "check" of the serial buffer every time and not block execution.

From reading through the ESPHome docs, they don't really like the ESP8266 boards.  They REALLY want you to use something ESP32-based so... maybe that's the problem?  Either way, the ESP32 code is a lot easier for me to test since... I'm running it myself haha.

**Comment by CJOWood** [comment]
> Try setting your logger section to "level: info" so you get less clutter. You'll just get the messages from my program then.
> 
> Yeah it's definitely getting SOME data. Not full packets for some reason though, that's really weird (should be 32 bytes of data received, it got 13, waited, and dumped it). There should be no activity on the line except for the ESP device, and it only sends a query packet every 15 seconds.  I'm also not sure why some of the components are taking so long for an operation, I tried to be sensitive to that and ensure that the code just does a drive-by "check" of the serial buffer every time and not block execution.
> 
> From reading through the ESPHome docs, they don't really like the ESP8266 boards.  They REALLY want you to use something ESP32-based so... maybe that's the problem?  Either way, the ESP32 code is a lot easier for me to test since... I'm running it myself haha.

Yeah, very bizarre. I was going through that HA forum thread where you initially posted and found another EspHome YAML to try out. It seems to partially work and I am getting some data but it does not make a ton of sense.

Ill switch to the ESP32 when it arrives!

**Comment by CJOWood** [comment]
@wtahler And I got it working! I am not exactly sure what got it going, but I am using your posted files exactly as they are, except for 1 change, which is to disable logging:
```
logger:
  baud_rate: 0
```

I will create a new issue, but the temperature readings are all in Fahrenheit but with "°C" after. I might need to find a way to convert before pulling into HA.

**Comment by wtahler** [comment]
Ah! Of course, the stupid logger was using the serial port! That's great, so glad you fixed it. I'll update the code now! And I'll checkout the Fahrenheit thing
